/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MailboxesIndexRouteImport } from './routes/mailboxes/index'
import { Route as MailboxesMailboxIdIndexRouteImport } from './routes/mailboxes/$mailboxId/index'
import { Route as MailboxesMailboxIdComposeRouteImport } from './routes/mailboxes/$mailboxId/compose'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MailboxesIndexRoute = MailboxesIndexRouteImport.update({
  id: '/mailboxes/',
  path: '/mailboxes/',
  getParentRoute: () => rootRouteImport,
} as any)
const MailboxesMailboxIdIndexRoute = MailboxesMailboxIdIndexRouteImport.update({
  id: '/mailboxes/$mailboxId/',
  path: '/mailboxes/$mailboxId/',
  getParentRoute: () => rootRouteImport,
} as any)
const MailboxesMailboxIdComposeRoute =
  MailboxesMailboxIdComposeRouteImport.update({
    id: '/mailboxes/$mailboxId/compose',
    path: '/mailboxes/$mailboxId/compose',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mailboxes/': typeof MailboxesIndexRoute
  '/mailboxes/$mailboxId/compose': typeof MailboxesMailboxIdComposeRoute
  '/mailboxes/$mailboxId/': typeof MailboxesMailboxIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mailboxes': typeof MailboxesIndexRoute
  '/mailboxes/$mailboxId/compose': typeof MailboxesMailboxIdComposeRoute
  '/mailboxes/$mailboxId': typeof MailboxesMailboxIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mailboxes/': typeof MailboxesIndexRoute
  '/mailboxes/$mailboxId/compose': typeof MailboxesMailboxIdComposeRoute
  '/mailboxes/$mailboxId/': typeof MailboxesMailboxIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/mailboxes/'
    | '/mailboxes/$mailboxId/compose'
    | '/mailboxes/$mailboxId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/mailboxes'
    | '/mailboxes/$mailboxId/compose'
    | '/mailboxes/$mailboxId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/mailboxes/'
    | '/mailboxes/$mailboxId/compose'
    | '/mailboxes/$mailboxId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MailboxesIndexRoute: typeof MailboxesIndexRoute
  MailboxesMailboxIdComposeRoute: typeof MailboxesMailboxIdComposeRoute
  MailboxesMailboxIdIndexRoute: typeof MailboxesMailboxIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mailboxes/': {
      id: '/mailboxes/'
      path: '/mailboxes'
      fullPath: '/mailboxes/'
      preLoaderRoute: typeof MailboxesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mailboxes/$mailboxId/': {
      id: '/mailboxes/$mailboxId/'
      path: '/mailboxes/$mailboxId'
      fullPath: '/mailboxes/$mailboxId/'
      preLoaderRoute: typeof MailboxesMailboxIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mailboxes/$mailboxId/compose': {
      id: '/mailboxes/$mailboxId/compose'
      path: '/mailboxes/$mailboxId/compose'
      fullPath: '/mailboxes/$mailboxId/compose'
      preLoaderRoute: typeof MailboxesMailboxIdComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MailboxesIndexRoute: MailboxesIndexRoute,
  MailboxesMailboxIdComposeRoute: MailboxesMailboxIdComposeRoute,
  MailboxesMailboxIdIndexRoute: MailboxesMailboxIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
