/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MailboxesIndexRouteImport } from './routes/mailboxes/index'
import { Route as MailboxesMailboxIdRouteImport } from './routes/mailboxes/$mailboxId'
import { Route as MailboxesMailboxIdIndexRouteImport } from './routes/mailboxes/$mailboxId/index'
import { Route as MailboxesMailboxIdComposeRouteImport } from './routes/mailboxes/$mailboxId/compose'
import { Route as MailboxesMailboxIdThreadIdRouteImport } from './routes/mailboxes/$mailboxId/$threadId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MailboxesIndexRoute = MailboxesIndexRouteImport.update({
  id: '/mailboxes/',
  path: '/mailboxes/',
  getParentRoute: () => rootRouteImport,
} as any)
const MailboxesMailboxIdRoute = MailboxesMailboxIdRouteImport.update({
  id: '/mailboxes/$mailboxId',
  path: '/mailboxes/$mailboxId',
  getParentRoute: () => rootRouteImport,
} as any)
const MailboxesMailboxIdIndexRoute = MailboxesMailboxIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MailboxesMailboxIdRoute,
} as any)
const MailboxesMailboxIdComposeRoute =
  MailboxesMailboxIdComposeRouteImport.update({
    id: '/compose',
    path: '/compose',
    getParentRoute: () => MailboxesMailboxIdRoute,
  } as any)
const MailboxesMailboxIdThreadIdRoute =
  MailboxesMailboxIdThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => MailboxesMailboxIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mailboxes/$mailboxId': typeof MailboxesMailboxIdRouteWithChildren
  '/mailboxes/': typeof MailboxesIndexRoute
  '/mailboxes/$mailboxId/$threadId': typeof MailboxesMailboxIdThreadIdRoute
  '/mailboxes/$mailboxId/compose': typeof MailboxesMailboxIdComposeRoute
  '/mailboxes/$mailboxId/': typeof MailboxesMailboxIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mailboxes': typeof MailboxesIndexRoute
  '/mailboxes/$mailboxId/$threadId': typeof MailboxesMailboxIdThreadIdRoute
  '/mailboxes/$mailboxId/compose': typeof MailboxesMailboxIdComposeRoute
  '/mailboxes/$mailboxId': typeof MailboxesMailboxIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mailboxes/$mailboxId': typeof MailboxesMailboxIdRouteWithChildren
  '/mailboxes/': typeof MailboxesIndexRoute
  '/mailboxes/$mailboxId/$threadId': typeof MailboxesMailboxIdThreadIdRoute
  '/mailboxes/$mailboxId/compose': typeof MailboxesMailboxIdComposeRoute
  '/mailboxes/$mailboxId/': typeof MailboxesMailboxIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/mailboxes/$mailboxId'
    | '/mailboxes/'
    | '/mailboxes/$mailboxId/$threadId'
    | '/mailboxes/$mailboxId/compose'
    | '/mailboxes/$mailboxId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/mailboxes'
    | '/mailboxes/$mailboxId/$threadId'
    | '/mailboxes/$mailboxId/compose'
    | '/mailboxes/$mailboxId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/mailboxes/$mailboxId'
    | '/mailboxes/'
    | '/mailboxes/$mailboxId/$threadId'
    | '/mailboxes/$mailboxId/compose'
    | '/mailboxes/$mailboxId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MailboxesMailboxIdRoute: typeof MailboxesMailboxIdRouteWithChildren
  MailboxesIndexRoute: typeof MailboxesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mailboxes/': {
      id: '/mailboxes/'
      path: '/mailboxes'
      fullPath: '/mailboxes/'
      preLoaderRoute: typeof MailboxesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mailboxes/$mailboxId': {
      id: '/mailboxes/$mailboxId'
      path: '/mailboxes/$mailboxId'
      fullPath: '/mailboxes/$mailboxId'
      preLoaderRoute: typeof MailboxesMailboxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mailboxes/$mailboxId/': {
      id: '/mailboxes/$mailboxId/'
      path: '/'
      fullPath: '/mailboxes/$mailboxId/'
      preLoaderRoute: typeof MailboxesMailboxIdIndexRouteImport
      parentRoute: typeof MailboxesMailboxIdRoute
    }
    '/mailboxes/$mailboxId/compose': {
      id: '/mailboxes/$mailboxId/compose'
      path: '/compose'
      fullPath: '/mailboxes/$mailboxId/compose'
      preLoaderRoute: typeof MailboxesMailboxIdComposeRouteImport
      parentRoute: typeof MailboxesMailboxIdRoute
    }
    '/mailboxes/$mailboxId/$threadId': {
      id: '/mailboxes/$mailboxId/$threadId'
      path: '/$threadId'
      fullPath: '/mailboxes/$mailboxId/$threadId'
      preLoaderRoute: typeof MailboxesMailboxIdThreadIdRouteImport
      parentRoute: typeof MailboxesMailboxIdRoute
    }
  }
}

interface MailboxesMailboxIdRouteChildren {
  MailboxesMailboxIdThreadIdRoute: typeof MailboxesMailboxIdThreadIdRoute
  MailboxesMailboxIdComposeRoute: typeof MailboxesMailboxIdComposeRoute
  MailboxesMailboxIdIndexRoute: typeof MailboxesMailboxIdIndexRoute
}

const MailboxesMailboxIdRouteChildren: MailboxesMailboxIdRouteChildren = {
  MailboxesMailboxIdThreadIdRoute: MailboxesMailboxIdThreadIdRoute,
  MailboxesMailboxIdComposeRoute: MailboxesMailboxIdComposeRoute,
  MailboxesMailboxIdIndexRoute: MailboxesMailboxIdIndexRoute,
}

const MailboxesMailboxIdRouteWithChildren =
  MailboxesMailboxIdRoute._addFileChildren(MailboxesMailboxIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MailboxesMailboxIdRoute: MailboxesMailboxIdRouteWithChildren,
  MailboxesIndexRoute: MailboxesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
